spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true
        spring.json.type.mapping: "org.wavemoney.payment.api.dto.event.NotificationEvent:org.wavemoney.notification.api.dto.event.NotificationEvent"

  data:
    mongodb:
      auto-index-creation: true
  mongodb:
    uri: mongodb://admin:password@localhost:27018/notification?authSource=admin

server:
  port: 8083

app:
  kafka:
    topics:
      transfer-events: payment.transfer.events
      cashin-events: payment.cashin.events
      cashout-events: payment.cashout.events
      transaction-events: payment.transaction.events
      notification-events: payment.notification.events

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.wavemoney.notification: DEBUG
